apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: order-dapr-config
spec:
  tracing:
    samplingRate: "1"
    otlp:
      endpointAddress: "http://localhost:4317"

  features:
    - name: Resiliency.V2Alpha
      enabled: true
    - name: WorkflowAlpha
      enabled: true

  metrics:
    enabled: true